- content/getting-started/index.md
Unclear as to what file the code is supposed to go in
> Unclear Code

- Jenkinsfile
- build.sh
- content/getting-started/index.md
- content/getting-started/os-x.md
- indexer.js
Arm y u do dis?
https://www.arm.com/company/policies/trademarks
Also important merge for Jenkins
> Conform with Arm Trademark Guidelines

- content/known-issues.md
see https://github.com/atom/flight-manual.atom.io/pull/365 for more info
> add information about incompatible packages

- config.toml
- content/api/index.md
In regards to purduesigbots/pros#34
> Reflects the introduction of ULTRA_BAD_RESPONSE

- content/tutorials/debugging.md
> Markdown header typo on Debugging page

- v5/okapi/api/chassis/controller/abstract-chassis-controller.rst
- v5/okapi/api/chassis/model/abstract-chassis-model.rst
- v5/okapi/api/chassis/model/skid-steer-model.rst
- v5/okapi/api/chassis/model/xdrive-model.rst
per OkapiLib/OkapiLib#202 and OkapiLib/OkapiLib#204
> rename chassismodel method parameters

- v5/tutorials/walkthrough/clawbot.rst
> remove colons from clawbot tutorial section titles

- v5/okapi/api/chassis/controller/abstract-chassis-controller.rst
- v5/okapi/api/chassis/controller/chassis-controller-integrated.rst
- v5/okapi/api/chassis/controller/chassis-controller-pid.rst
- v5/okapi/api/chassis/model/skid-steer-model.rst
- v5/okapi/api/chassis/model/three-encoder-skid-steer-model.rst
- v5/okapi/api/chassis/model/xdrive-model.rst
- v5/okapi/api/control/async/async-linear-motion-profile-controller.rst
- v5/okapi/api/control/async/async-motion-profile-controller.rst
- v5/okapi/api/control/async/async-pos-integrated-controller.rst
- v5/okapi/api/control/async/async-pos-pid-controller.rst
- v5/okapi/api/control/async/async-vel-integrated-controller.rst
- v5/okapi/api/control/async/async-vel-pid-controller.rst
- v5/okapi/api/control/async/async-wrapper.rst
- v5/okapi/api/control/iterative/iterative-motor-velocity-controller.rst
- v5/okapi/api/control/util/pid-tuner.rst
- v5/okapi/api/filters/composable-filter.rst
- v5/okapi/api/filters/vel-math.rst
Changes reflects OkapiLib/OkapiLib#245
> Docs for OkapiLib PR 245

- v5/blog/doom.rst
Pretty cool use of PROS, thought it deserved a blog post.
> Doom Blog Post

- v5/tutorials/topical/display.rst
> Update LVGL tutorial

- v5/api/c/vision.rst
Added periods for consistency with the previous formatting/punctuation.
> Add periods to vision.rst

- v5/getting-started/linux.rst
Extra instructions regarding restarting after installation added.
> Update linux installation instructions

- v5/okapi/api/device/button/abstract-button.rst
Docs for OkapiLib/OkapiLib#323
> Add AbstractButton::controllerGet() docs

- v5/tutorials/topical/adi.rst
- v5/tutorials/walkthrough/clawbot.rst
GEARSET_36 TO MOTOR_GEARSET_36 in two places for consistency throughout the tutorial
> MOTOR_GEARSET

- v5/tutorials/topical/adi.rst
- v5/tutorials/walkthrough/clawbot.rst
A simple autonomous program for the Clawbot walkthrough.
> Autonomous

- v5/okapi/tutorials/walkthrough/autonomous-movement-basic.rst
> Remove dead okapi tutorial link

- home/_static/report.html
See https://sentry.io/purdue-acm-sigbots/pros-cli-testing/issues/755342933/feedback/ for an example of how the feedback looks for us.
> Add Sentry user reports page

- v5/okapi/tutorials/index.rst
> Order Okapi Walkthrough Tuts

- home/_templates/index.html
Currently in the licensing at the bottom 2018 hasnt been updated to 2019
> Update legal to 2019 in index.html

- v5/okapi/tutorials/walkthrough/clawbot.rst
The okapi clawbot tutorial had some misinformation which these changes should address.
> Update okapi clawbot tutorial

- v5/okapi/api/control/async/async-motion-profile-controller.rst
I honestly don't know if this is going to work, I couldn't get it to build.
> Add docs for save/load Pathfinder paths

- v5/okapi/api/device/motor/abstract-abstract-motor.rst
- v5/okapi/api/device/motor/motor-group.rst
- v5/okapi/api/device/motor/motor.rst
See https://github.com/OkapiLib/OkapiLib/pull/365
> Add docs for position/velocity error methods

- v5/tutorials/general/coding-faq.rst
>  Add "main.h" file not found to Coding FAQ

- v5/api/c/adi.rst
- v5/api/c/motors.rst
- v5/api/c/vision.rst
- v5/api/cpp/adi.rst
- v5/api/cpp/motors.rst
- v5/api/cpp/vision.rst
Update errno documentation to be consistent with purduesigbots/pros#129
> Update errno documentation to be consistent with purduesigbots/pros#129

- v5/api/cpp/motors.rst
> Fix bad motor_fault_e_t documentation

- v5/releases/kernel3.2.0.rst
Draft release notes for kernel 3.2.0
> draft release notes

- v5/api/c/adi.rst
- v5/api/c/motors.rst
- v5/api/c/vision.rst
- v5/api/cpp/adi.rst
- v5/api/cpp/motors.rst
- v5/api/cpp/rtos.rst
- v5/api/cpp/vision.rst
- v5/releases/kernel3.2.0.rst
- v5/tutorials/general/project-structure.rst
- v5/tutorials/walkthrough/clawbot.rst
- v5/tutorials/walkthrough/creating-c-project.rst
> Kernel release 3.2.0 documentation

- v5/api/c/rtos.rst
- v5/api/cpp/rtos.rst
This is my first time contributing to the docs, lmk if I did something wrong
> add documentation for task_notify_t enum

- v5/api/c/vision.rst
- v5/api/cpp/rtos.rst
- v5/api/cpp/vision.rst
I noticed a couple warnings when checking out #154. This fixes some of them.
> Fixed a couple warnings

- v5/api/c/adi.rst
Found this while trying to figure out the API while writing code that used the API, and thought it would be useful to include int he docs.
> Clarify return value on ADI init errors

- v5/getting-started/new-users.rst
Could be expanded with a brief Git tutorial (what commits are, how to create a GitHub repo, etc.) since many programmers may not have previously used a version control system.
> Add paragraph explaining what Git/GitHub is

- v5/getting-started/new-users.rst
As per discussion with @HotelCalifornia . Please let me know if this isn't a good place for it or if the wording should be changed at all.
> Add reference to QUEEN Educational Resources YouTube playlist

- v5/api/cpp/motors.rst
- v5/api/cpp/vision.rst
Docs for https://github.com/purduesigbots/pros/pull/188 
No docs for serial since we don't have any.
> Add get port docs

- v5/api/cpp/rtos.rst
> add docs for pros#177

- v5/api/c/misc.rst
- v5/api/cpp/misc.rst
Docs for https://github.com/purduesigbots/pros/pull/189/files
> Added usd docs

- v5/releases/kernel3.2.1.rst
> add 3.2.1 release notes

- v5/api/c/misc.rst
- v5/api/cpp/misc.rst
docs for https://github.com/purduesigbots/pros/pull/169/files
This is the last of them.
> Controller clear

- v5/api/cpp/rtos.rst
Docs for https://github.com/purduesigbots/pros/pull/182 that I initially missed.
> Fix up docs for task

- v5/api/cpp/adi.rst
- v5/tutorials/topical/adi.rst
> ADI Updates and Fixes

- v5/api/cpp/imu.rst
> Fix Inertial Sensor Typos

- home/_static/css/row.css
- home/_templates/index.html
- v5/conf.py
Add Sponsors and Updated Copyright to 2020
> Add Sponsors

- v5/api/c/adi.rst
- v5/api/c/adi_ext.rst
- v5/api/c/misc.rst
- v5/api/c/rtos.rst
- v5/api/cpp/adi.rst
- v5/api/cpp/misc.rst
- v5/api/cpp/rtos.rst
- v5/api/index.rst
- v5/extended/apix.rst
- v5/okapi/api/device/controller.rst
- v5/releases/kernel3.3.0.rst
* Added docs for ADI Expander
* Added Release Notes
> 🔖 3.3.0 Release

- v5/api/c/distance.rst
- v5/api/c/optical.rst
- v5/api/c/rotation.rst
- v5/api/cpp/distance.rst
- v5/api/cpp/optical.rst
- v5/api/cpp/rotation.rst
- v5/api/index.rst
- v5/releases/kernel3.3.1.rst
> 🔖 3.3.1 Release

- v5/api/api-legacy.rst
- v5/api/c/llemu.rst
- v5/api/cpp/imu.rst
- v5/api/cpp/llemu.rst
- v5/tutorials/topical/adi.rst
- v5/tutorials/topical/llemu.rst
Fixed up all instances where an infinite while loop was in initialize.
Before:
After:
Related Issue:
#191
> Infinite While Loops in Initialize Fix

- v5/api/c/motors.rst
- v5/api/cpp/motors.rst
Added notes about motor functions not respecting brake mode.
> Motor Functions not Respecting Brake Mode

- v5/getting-started/macos.rst
- Adds install information about vision utility
> Add Vision Sensor Utility Install to MacOS Install Page

- v5/tutorials/topical/vision.rst
Summary:
- Shows how to create signatures programmatically. 
- Shows how to create color codes. 
Closed #70
> Update Vision Sensor Topical Tutorial

- v5/extended/multitasking.rst
Add that you can delete a recursive mutex with mutex_delete.
> Add recursive mutex deletion to docs

- v5/getting-started/macos.rst
cask install has been depreciated.
> Change Install cask to --cask

- v5/api/c/imu.rst
- v5/api/cpp/imu.rst
Added documentation for the reset functions (tare and set) for the IMU.
> Update IMU Docs for 3.4.0

- v5/tutorials/topical/adi.rst
- v5/tutorials/topical/controller.rst
- v5/tutorials/topical/llemu.rst
- v5/tutorials/topical/motors.rst
- v5/tutorials/topical/multitasking.rst
- v5/tutorials/topical/vision.rst
fixes #215 by swapping the order of all the C and C++ files
> swapped c and cpp order in tutorials

- v5/tutorials/topical/multitasking.rst
fixes #213 and replaces the discussion with an explanation of atomic variables.
> Fix multithreaded synchronization

- v5/cli/conductor.rst
- v5/cli/index.rst
- v5/getting-started/linux.rst
- v5/getting-started/macos.rst
- v5/okapi/tutorials/walkthrough/clawbot.rst
- v5/okapi/tutorials/walkthrough/getting-started.rst
- v5/releases/cli3.2.0.rst
- v5/tutorials/general/debugging.rst
- v5/tutorials/walkthrough/clawbot.rst
- v5/tutorials/walkthrough/uploading.rst
- Created CLI Release Notes
- Updated mentions of prosv5 to pros where applicable.
> 3.2.0 CLI Release notes

- v5/api/cpp/optical.rst
> fixed typo in optical example

- v5/getting-started/windows.rst
fixes #227 to try to help users determine what file they need to download
> specified other files and gave way to find operating system type

- v5/releases/cli3.2.1.rst
* Add release notes for CLI 3.2.1 release
> CLI 3.2.1 Release Notes

- v5/api/c/gps.rst
- v5/api/cpp/gps.rst
- v5/api/cpp/motors.rst
- v5/api/index.rst
Added the new GPS API Documentation, please review and let me know if there are any mistakes or enhancements to make.
> GPS API Documentation

- v5/api/c/gps.rst
- v5/api/cpp/gps.rst
- v5/releases/kernel3.5.1.rst
Add Release blog, file, and gps fixes. Prepare for release.
> Add Release blog, file, and gps fixes

- v5/releases/kernel3.5.2.rst
Added the 3.5.2 release notes and zip of the template.
> Kernel 3.5.2 Release Notes

- v5/tutorials/walkthrough/clawbot.rst
Need to update the other C functions so they compile as well
> Changed the C code so it actually compiles

- azure-pipelines.yml
Change to job setup with `ubuntu-latest`
> Fix CI for old Ubuntu VM

- requirements.txt
See here for why: [sphinx-doc/sphinx#9727]( https://github.com/sphinx-doc/sphinx/issues/9727)
> Fixes issue with Sphinx and docutils

- v5/api/c/optical.rst
- v5/api/cpp/misc.rst
Says what it does on the label, various fixes for our documentation.
Closes:
#254
> Added optical_raw_s fix and fix to example code for controller set text

- v5/cli/conductor.rst
would be cool if someone could test this---i'm not convinced my RST is exactly correct
> add guide on creating remote depots and more

- v5/tutorials/topical/notifications.rst
added some (imo much needed) information to the task notifications tutorial, including some common use-cases regarding advanced task lifecycle control. actually tested the RST output on this one
> update task notifications docs

- v5/tutorials/topical/display.rst
Fixed a broken link to the old lvgl website
> Fix broken link in docs

- home/_templates/index.html
- v5/conf.py
> Update year number for copyright info

- v5/api/c/gps.rst
- v5/api/c/link.rst
- v5/api/cpp/link.rst
- v5/api/index.rst
> Vex link docs

- v5/api/c/screen.rst
- v5/api/cpp/screen.rst
Includes mentioning of error handling (EACCESS and PROS_ERR ret val)
> Screen Docs Updates for 3.6

- v5/api/c/rtos.rst
- v5/api/cpp/rtos.rst
> Task join docs

- v5/releases/kernel3.6.0.rst
Release notes for update 3.6.0.
> Kernel release 3.6.0

- home/_templates/index.html
This intends to bring our front page descriptions to a more up to date state. I'd like some feedback on what else I should add/remove from the description of our main page though.
> Change Cortex Descriptions to V5

- v5/api/c/rotation.rst
- v5/api/cpp/rotation.rst
Docs for the new rotation sensor reverse flag constructor.
> Add docs for reverse init constructor

- v5/releases/cli3.3.2.rst
> Add release notes for 3.3.2 CLI release

- home/_static/css/mvp.css
- home/_templates/index.html
Updated font, corner radius, and image width.
> Slight Changes

- v5/api/c/link.rst
- v5/api/cpp/link.rst
Add a note about the limit of one radio per brain to the link docs
> Port claim radio

- v5/api/c/imu.rst
- v5/api/cpp/imu.rst
Also fixed up the IMU docs with the C++ unnecessary port param.
> Add IMU Blocking Reset Documentation

- v5/api/c/screen.rst
- v5/api/cpp/screen.rst
We changed/fixed the callback API, these are the changes to the docs reflecting it.
> Add updates to screen callback code

- v5/api/c/motors.rst
- v5/api/cpp/motors.rst
Update Docs with Motor Gearset Aliases
> Motor Gearset Alias

- v5/api/c/link.rst
- v5/api/cpp/link.rst
> Add Enum Aliases that were forgotten for VEXLink

- v5/api/c/vision.rst
- v5/api/cpp/vision.rst
> Use the correct data types

- home/_templates/index.html
- v5/conf.py
> Update Year to 2023

- v5/tutorials/walkthrough/clawbot.rst
> Change Atom reference to VSCode

- v5/getting-started/macos.rst
Reverts purduesigbots/pros-docs#337
> Revert "Updated Arm GNU Toolchain download link"

- azure-pipelines.yml
- scripts/build.sh
Testing instructions:
download the artifact from azure.
extract it
see if there is v5/pros-4 folder with HTML documents
> Adds PROS 4 to main docs site using pipelines

- v5/api/cpp/gps.rst
gps_get ... 
should be 
get ...
> Cpp wrong header name docs

- v5/releases/kernel4.0.7
Upload files for kernel 4.0.7 release
> 🔖Kernel 4.0.7 release

- v5/_static/releases/pros-mainline.json
- v5/releases/kernel4.1.0.rst
Docs and actually release PROS 4
> PROS 4 release

- v5/_static/beta/testing-mainline.json
Add a kernel version with a new libm to testing mainline
> Add a kernel version with a new libm to testing mainline
