purduesigbots/pros-docs

content/api/index.md
Per request on Discord, elaborates that values of 1 and 2 are valid for the functions `isJoystickConnected, `joystickGetDigital`, and `joystickGetAnalog`
=> Elaborate on valid values for joystick functions

content/getting-started/windows.md
Per purduesigbots/pros#16, add information about how to manually add Atom to PATH in case of installer failure
TODO: I'll add relevant Windows 10 instructions once I get home to ~~a real~~ my computer
=> Add add'l info to Windows PATH issue workaround

content/getting-started/index.md
Corrected the joystick description in the arcade control example.
=> Arcade control uses the right joystick, not left

content/upgrading.md
As it turns out, the link provided in the Atom plugin (http://pros.cs.purdue.edu/upgrading) didn't exist.
(Also as a side note, the CLI actually has no logic for detecting installations on platforms other than on Windows, so this could help to clear that up a little)
=> Add instructions for upgrading the PROS environment

v5/extended/apix.rst, v5/getting-started/new-users.rst, v5/tutorials/general/coding-faq.rst, v5/tutorials/general/debugging.rst
Hey guys,
Love the v5 documentation.  Noticed you added some subfolders to the tutorials section a while back which caused some links to break.  Hope this might help?
Also - massive thanks to the gentleman who helped troubleshoot my PROS install for the software stations at VEX Worlds.  We got exactly what we needed, and he was super helpful and gracious about it.  :)
=> Fix broken links by adding subfolders to path

v5/tutorials/topical/display.rst, v5/tutorials/topical/llemu.rst
Putting too much information in an LVGL tutorial is redundant with their own docs, but it's probably worth adding a tutorial for it to help point users towards the LVGL site (compared to the single link in the extended API currently), since so many users are asking about it.
I think the main goal is to help redirect users to LVGL's site as opposed to explaining the ins and outs of the library ourselves, but I'm definitely open to suggestions on that.
=> Add LVGL tutorial

cortex/tutorials/known-issues.rst
Fixed minor typo in cortex/tutorials/known-issues.rst
Changed ```wirless``` to ```wireless```
Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>
=> cortex/tutorials: fixed typo

v5/tutorials/walkthrough/clawbot.rst
The same files were referred to by different names on the same page of the docs. Looks like probably due to copying over from cortex docs.
=> update file names for consistency

v5/tutorials/topical/adi.rst
Closes #93. The API description was correct, but the tutorial never got updated to match.
=> Fix the port description for ultrasonic tutorial

v5/okapi/tutorials/index.rst
From [this forum post](https://www.vexforum.com/t/okapilib-help/56982), I took a look at the tutorials page and saw that the order of tutorials wasn't that great. You probably want to start at "Getting started", then look at "clawbot", and so on.
Tradeoff is that you're gonna have to manually include future walkthrough tutorials, but at least they'll be an order that's easier for someone taking a first look at Okapi to get a grasp on what's going on.
=> Order Okapi Walkthrough Tuts

home/_templates/index.html
Changed PROS 2 download link to point to the last PROS 2 release, since the [purduesigbots/pros](https://github.com/purduesigbots/pros/) repo now includes PROS 3 releases too
=> Fixed PROS 2 download link

v5/tutorials/topical/adi.rst
Fixes an issue in the ADI page where the code for the line tracker had the line
`while(sensor.get_value < 2000) {`
when the correct line is
`while(sensor.get_value() < 2000) {`
resolves #116
=> Update ADI tutorial

v5/okapi/tutorials/walkthrough/clawbot.rst
Looks like a couple of things were missed with #120, this should just fix the remaining issues having to do with `move_voltage()` being used instead of `moveVoltage()`.
=> More fixes to okapi clawbot tutorial

v5/tutorials/topical/filesystem.rst
This PR rewords the filesystem tutorial so it is clearer that you cannot use the filesystem API with the V5 brain's flash.
=> Reword filesystem tutorial

.gitignore, .gitmodules
This PR adds `venv` to the gitignore and amends gitmodules so it ignores a dirty sphinx-tabs, which occurs when you build.
=> Ignore venv and sphinx-tabs dirty

v5/getting-started/linux.rst
various problems motivate this change: 
- the Ubuntu PPA doesn't seem to be updated anymore
- Debian users couldn't even use that PPA without jumping through some hoops in the first place
- Apt has a badly outdated version.
thus, I have updated the instructions once again with a foolproof method that involves adding Arm's the contents of Arm's prebuilt archive for linux on PATH.
=> Update toolchain instructions again

v5/releases/kernel3.2.0.rst, v5/tutorials/general/project-structure.rst, v5/tutorials/walkthrough/clawbot.rst, v5/tutorials/walkthrough/creating-c-project.rst
I somehow forgot to mention that new projects will by default now have a src/main.cpp instead of the three files we had previously. This PR goes through and changes that for all the tutorials and stuff as well.
=> update references to opcontrol et al

v5/index.rst
Closes #153. 
I wanted to verify that this change works properly, but I'm stuck not being able to build locally because of what looks like a Sphinx error (sphinx-doc/sphinx#6722).
=> Fix uploading doc link on V5 Home Page

v5/conf.py
Not sure why I was experiencing this issue and not Azure or other devs, but it looks like the `blog_baseurl` value is required for proper compilation with ablog. Further discussion can be found in sunpy/ablog#43.
=> Fix compilation issue with Ablog

v5/contact.rst
The Slack link on the main website under getting help was expired so here is a replacement
=> Replaces Expired Slack Link

v5/tutorials/topical/filesystem.rst
Currently, we don't have the format the SD Card needs to be in anywhere in the docs, so add it. The tutorial section isn't the best place for it, but we don't really touch this anywhere else that I know of.
=> Add sd card formatting requirement

v5/api/cpp/motors.rst
This PR fixes the `Motor::move` docs so that they are consistent with the latest release's header file.
Closes #108.
=> Fix motor move docs

v5/api/cpp/imu.rst
Check out if the `reset() `function's example makes sense. I also think the `get_status()` example needs to be changed but I don't know what would be good example to put in there.
=> Fixed IMU documentation to change reset function example

v5/api/c/motors.rst, v5/api/cpp/motors.rst
This PR fixes a typo in the C and C++ versions of the `set_zero_position` docs.
=> Fix set zero position docs

v5/contact.rst
Fixed link leading to VF's PROS section, located on this page: https://pros.cs.purdue.edu/v5/contact.html
Replaced first link with updated link that works with the new VEXForum update (that happened about a year ago)
=> Contact Us Link Fix

home/_templates/index.html
Currently, the image link to StickerMule does not have a closing </a> tag, so everything below it (including the PROS logo in the footer and the license info, up to the link in the copyright) links to StickerMule.
This PR adds a </a> tag so that the rest of the page behaves normally.
=> Fix missing </a> in StickerMule link

v5/api/c/optical.rst, v5/api/c/rotation.rst, v5/api/cpp/optical.rst, v5/api/cpp/rotation.rst
Changes:
-Fixed syntax highlighting and analogous functions on C pages for optical and rotation sensors.
-Fixed everything under get_hue for the optical C++ pages not showing up.
=> Rotation/Optical Page Fixes

v5/api/c/rotation.rst, v5/api/cpp/rotation.rst
Added clarifications to get_angle as to what centidegrees entails to reflect kernel header documentation changes as detailed in the attached issue (#203).
=> Clarifications to Rotation Sensor's get_angle Documentation

requirements.txt, v5/cli/conductor.rst
Removes pros-cli-v5 from requirements.txt.
closes #122
=> Remove pros-cli-v5 from requirements.txt

v5/api/cpp/vision.rst
This PR documents the default parameters for create_color_code in the cpp page.
Note: We should also update the kernel header files when we work on PROS 4 for this, as the switch to doxygen would make this somewhat necessary so the docs show the default params properly.
=> Added documentation for create_color_code's default params

v5/getting-started/linux.rst
Adds a note to Linux installation that some Linux distributions may need to install arm-eabi-none-newlib
=> added note about installing arm-none-eabi-newlib

v5/getting-started/macos.rst
On [https://pros.cs.purdue.edu/v5/getting-started/macos.html](https://pros.cs.purdue.edu/v5/getting-started/macos.html), the first note reads that you should replace step 3 with `brew install pros-cli`. 
However step 3 currently says to add the pros homebrew repository. As far as I can tell you need that to install the pros cli, and step 4 which installs the pros editor would be the command that is replaced.
=> Change step number on the notice to line up with the main tutorial

v5/tutorials/topical/wireless-upload.rst
Updated page to talk about how hot/cold linking is enabled by default, as well as a warning relating to mismatched kernel versions (see #233).
=> Update Hot/Cold Linking

README.md
Currently the README.md still contains a broken link to https://github.com/purduesigbots/pros3, the old V5 repository. As the two have since then been merged into https://github.com/purduesigbots/pros, I've gone ahead and removed the outdated reference.
=> Remove 404 "PROS for V5" repository link

v5/api/cpp/screen.rst
Seems like there was a bit of a typo in the new Screen API documentation, as ``set_eraser`` has ``set_pen`` in the Prototype panel.
=> Fix set_eraser referencing the wrong prototype

v5/api/c/adi_ext.rst
The example documentation for ext_adi_pin_mode was missing the smart port parameter. This PR fixes that.
- Added ADI_EXPANDER_PORT parameter to example usage of ext_adi_pin_mode.
=> Fix typo in example for ext_adi_pin_mode

v5/api/c/rtos.rst, v5/api/cpp/rtos.rst
Adds both `task_get_current()` and `pros::Task::current()` to the docs to match the current API in PROS.
=> Added `task_get_current` to the C and C++ docs

v5/api/cpp/gps.rst
Extremely small typo with a missing " in a string inside of a print statement.
=> Fix Quotations, add gps_status_s_t to pros::c

v5/api/c/motors.rst, v5/api/cpp/motors.rst
Both the C `motor_get_voltage()` function and the C++ `Motor.get_voltage()` function claimed in the documentation to return doubles, but actually returned integers. This updates the documentation and example code to match the actual return values (based on the function declarations).
=> Fix return type of motor_get_voltage()

v5/tutorials/topical/filesystem.rst
Should close stderr, not usd_file_write.
=> Fix variable name in Serial section of Filesystem

v5/api/api-legacy.rst
The note in analog calibrate said that the new update time for ADI sensors was 50ms, which was incorrect and I changed it 10 ms.
=> Change note in analog calibrate to reflect 10ms update intervals from the ADI sensors

v5/api/cpp/vision.rst
Some variable names are "sensor" or "vis". Renamed all to "vision_sensor".
=> Fixed parity between names of vision_sensor declarations.

v5/tutorials/topical/vision.rst
There were some occurrences of vision sensor being declared as "vision_sensor" and then when referenced later called as "sensor" or "vis".
=> Fixed variable name of vision_sensor to match its declaration.

v5/api/cpp/motor_groups.rst
Found and fixed some typos in the examples in the motor group docs.
=> Fixed typos in motor group docs

v5/api/cpp/rotation.rst
`reset` method had `reverse`'s prototype
=> Fix Typo in Rotation::reset() Prototype

v5/getting-started/macos.rst
The previous link went to a deprecated page.
=> Updated Arm GNU Toolchain download link

v5/api/cpp/link.rst
Changes:
- Switch `LINK_RECEIVER_PORT` to `LINK_TRANSMITTER_PORT` where applicable
- Change the spelling of `RECIVER` to `RECEIVER` when possible (unable to do so in "Enumerated Values" section in order to maintain compatibility with the PROS source)
- Switch incorrect `receive` and `transmit` words
- Change one instance of `reciever_raw` to say `receive_raw`
=> Fix typos/incorrect words in link docs

v5/api/cpp/motor_groups.rst
The get_current_draws method of the Motor_Groups class was listed as a configuration function, and not a telemetry function.
=> Corrected the location of the get_current_draws method

.gitmodules
Testing to see if adding mainline to the docs repo will allow the mainline jsons to be reachable from a pros.cs.purdue.edu domain
=> add mainline to docs repo as submodule

.gitmodules
Removes mainline as a submodule. Will copy the Jsons into the repo as a next pr
=> Remove Mainline as a submodule

v5/extended/apix.rst
LVGL project has abandoned the littlevgl.com domain so fix the link to an archive of the docs for lvgl 5.3
=> 🐛change link to lvgl 5.3 archive

scripts/build.sh, v5/index.rst, v5/pros-4/index.rst
Tested locally on pros mac and it generates links to the pros 4 docs correctly
=> ✨Adds a sidebar entry for pros-4 docs

v5/api/c/motors.rst
The Motors C++ API contains information about the E_MOTOR_BRAKE_BRAKE enum value for motor_brake_mode_e_t. However, this information is not present in the corresponding C API page. This PR (just 1 commit) just copies over the information from the C++ API page to the C API page
=> Motors C API: Add info on E_MOTOR_BRAKE_BRAKE

v5/_static/releases/pros-mainline.json, v5/api/c/imu.rst, v5/api/cpp/imu.rst, v5/releases/kernel3.8.3.rst
Adds Documentation and Template for kernel 3.8.3
Fixes the critical bug that prevented IMUs from getting reset. 
Added Get_orientation capabilities
=> Kernel 3.8.3 Release

v5/api/cpp/motors.rst
The Motor cpp docs incorrectly stated the signature for `is_stopped` as 
```
std::int32_t motor_is_stopped ( )
```
when the correct signature is
```
std::int32_t pros::Motor::is_stopped()
```
This PR fixes that discrepancy.
=> Fix typo in Motor cpp docs
